#!/usr/bin/perl
use warnings;
use strict;
use 5.26.3;
use Data::Dumper;

# tried to use the file::slurp library but cpan doesn't work lol
# use File::Slurp

sub json_to_hash{
    # load args
    my $path = shift;
    my $hash_ref = shift;
    open(my $fh, '<', $path) or die "can't open $path";

    # loop through all lines in the json file
    while (my $line = <$fh>){
        # say $line;
        if ($line =~ /"([^"]+)"\s*:\s*([^"]+)/){
            my $key = $1;
            my $value = $2;
            
            # if the value has a comma at the end, chop it
            # chop off new line first
            chop($value);
            if ($value =~ /,$/){
                # say "chopping";
                chop($value);
            }

            # say "$key $value";

            # doesn't support subkeys at this point:
            if ($value eq "{"){
                die "\033[31mdoesn't support subkeys\033[0m";
            } 
            @$hash_ref{$key} = $value;
        }
    }
}

# return log2(arg)
sub log2{
    my $arg = shift;
    return log($arg)/log(2);
}


my $sv_file = 'hdl/mp_cache_data_array_pl.sv';
my $json_file = 'sram_config.json';
my %config;

# read json file
json_to_hash($json_file, \%config);
# print Dumper(\%config);

# sram array generation in perl '>' stand for write
open(my $sv_fh, '>', $sv_file);

# generate header
print $sv_fh "// generated by pl_generate_sram.pl \n";
foreach my $key (sort keys %config){ # sort keys in alphabetical order
    my $value = $config{$key};
    print $sv_fh "// $key : $value \n";
}

# set up ports and calculate all the params
# perl uses () instead of [] for array/dict
my @input_ports = ("csb", "web", "wmask", "addr", "din");
my @output_ports = ("dout");
my $input_header = "\tinput\tlogic\t";
my $output_header = "\toutput\tlogic\t";
my $param_header = "\tparameter";
my $logic_header = "\tlogic\t";

my $data_width = int($config{"word_size"});
my $addr_width = int(log2($config{"num_words"}));
# say "addr_width is $addr_width";
my $num_wmasks = int($data_width/8);
my $ram_depth = int($config{"num_words"});


# start populating the params
print $sv_fh "module mp_cache_data_array_pl\n#(\n";
print $sv_fh "$param_header NUM_WMASKS = $num_wmasks,\n";
print $sv_fh "$param_header DATA_WIDTH = $data_width,\n";
print $sv_fh "$param_header ADDR_WIDTH = $addr_width,\n";
print $sv_fh "$param_header RAM_DEPTH  = $ram_depth \n)\n(\n";

# start populating ports
print $sv_fh "\tinput\tlogic\tclk,\n\n";

# generate output ports based on number of ports
for (my $port_idx = 0; $port_idx < $config{"num_rw_ports"}; $port_idx++){
    print $sv_fh "\t// port $port_idx\n";

    # loop through all input ports
    foreach my $port (@input_ports){
        if ($port eq "addr"){
            print $sv_fh "$input_header\[ADDR_WIDTH-1: 0\]\t$port$port_idx,\n";
        }elsif ($port eq "din"){
            print $sv_fh "$input_header\[DATA_WIDTH-1: 0\]\t$port$port_idx,\n";
        }elsif ($port eq "wmask"){
            print $sv_fh "$input_header\[NUM_WMASKS-1: 0\]\t$port$port_idx,\n";
        }else{
            print $sv_fh "$input_header$port$port_idx,\n";
        }
    }

    foreach my $port (@output_ports){
        if ($port eq "dout"){
            print $sv_fh "$output_header\[DATA_WIDTH-1: 0\]\t$port$port_idx";
        }else{
            print $sv_fh "$output_header$port$port_idx";
        }
        # if this is not the last port we need to write, then add comma 
        if (($port eq $output_ports[$#output_ports]) && 
            ($port_idx == ($config{"num_rw_ports"} - 1))){
            print $sv_fh "\n";
        }else{
            print $sv_fh ",\n";
        }
    }

}

# close the () for ports declaration
print $sv_fh "\n);\n";

# declare local logic
for (my $port_idx = 0; $port_idx < $config{"num_rw_ports"}; $port_idx++){
    print $sv_fh "\t// port $port_idx\n";

    # loop through all logic ports
    foreach my $port (@input_ports){
        if ($port eq "addr"){
            print $sv_fh "$logic_header\[ADDR_WIDTH-1: 0\]\t$port$port_idx\_reg;\n";
        }elsif ($port eq "din"){
            print $sv_fh "$logic_header\[DATA_WIDTH-1: 0\]\t$port$port_idx\_reg;\n";
        }elsif ($port eq "wmask"){
            print $sv_fh "$logic_header\[NUM_WMASKS-1: 0\]\t$port$port_idx\_reg;\n";
        }else{
            print $sv_fh "$logic_header$port$port_idx\_reg;\n";
        }
    }

    foreach my $port (@output_ports){
        if ($port eq "dout"){
            print $sv_fh "$logic_header\[DATA_WIDTH-1: 0\]\t$port$port_idx\_reg;\n";
        }else{
            print $sv_fh "$logic_header$port$port_idx\_reg;\n";
        }
    }
}
print $sv_fh "$logic_header\[DATA_WIDTH-1: 0]\tmem [RAM_DEPTH]; \n";

# generate latch logic
print $sv_fh "\n\n\t // latch input value";
print $sv_fh "\n\talways_ff @ (posedge clk) begin\n";
for (my $port_idx = 0; $port_idx < $config{"num_rw_ports"}; $port_idx++){
    print $sv_fh "\t\tif (!csb$port_idx) begin\n";
    print $sv_fh "\t\t\tweb$port_idx\_reg <= web$port_idx;\n";
    print $sv_fh "\t\t\twmask$port_idx\_reg <= wmask$port_idx;\n";
    print $sv_fh "\t\t\taddr$port_idx\_reg <= addr$port_idx;\n";
    print $sv_fh "\t\t\tdin$port_idx\_reg <= din$port_idx;\n";
    print $sv_fh "\t\tend\n";
}
# close this always_ff block
print $sv_fh "\tend\n \n ";

# generate write logic
print $sv_fh "\n\talways_ff @ (posedge clk) begin\n";
for (my $port_idx = 0; $port_idx < $config{"num_rw_ports"}; $port_idx++){
    print $sv_fh "\t\tif (!web$port_idx\_reg) begin\n";
    for (my $idx = 0; $idx < $num_wmasks; $idx++){
        my $begin_idx = $idx * 8;
        my $end_idx = $idx * 8 + 7;
        print $sv_fh "\t\t\tif (wmask$port_idx\_reg[$idx]) \n";
        print $sv_fh "\t\t\t\tmem[addr$port_idx\_reg][$end_idx:$begin_idx] <= din$port_idx\_reg[$end_idx:$begin_idx];\n";
    }    
}

# end both the if and always ff
print $sv_fh "\t\tend\n";
print $sv_fh "\tend\n\n";

# generate read logic
for (my $port_idx = 0; $port_idx < $config{"num_rw_ports"}; $port_idx++){
    print $sv_fh "\tassign dout$port_idx = mem[addr$port_idx\_reg];";
}
print $sv_fh "\n\n";
# end module
print $sv_fh "endmodule";
# close file handler when done
close $sv_fh