#!/usr/bin/perl
use warnings;
use strict;
use 5.26.3;
use Data::Dumper;

# tried to use the file::slurp library but cpan doesn't work lol
# use File::Slurp

sub json_to_hash{
    # load args
    my $path = shift;
    my $hash_ref = shift;
    open(my $fh, '<', $path) or die "can't open $path";

    # loop through all lines in the json file
    while (my $line = <$fh>){
        say $line;
        if ($line =~ /"([^"]+)"\s*:\s*([^"]+)/){
            my $key = $1;
            my $value = $2;
            
            # if the value has a comma at the end, chop it
            # chop off new line first
            chop($value);
            if ($value =~ /,$/){
                say "chopping";
                chop($value);
            }

            say "$key $value";

            # doesn't support subkeys at this point:
            if ($value eq "{"){
                die "\033[31mdoesn't support subkeys\033[0m";
            } 
            @$hash_ref{$key} = $value;
        }
    }
}


my $sv_file = 'hdl/mp_cache_data_array_pl.sv';
my $json_file = 'sram_config.json';
my %config;

# read json file
json_to_hash($json_file, \%config);
print Dumper(\%config);

# sram array generation in perl '>' stand for write
open(my $sv_fh, '>', $sv_file);

# generate header
print $sv_fh "// generated by pl_generate_sram.pl \n";
foreach my $key (sort keys %config){ # sort keys in alphabetical order
    my $value = %config{$key};
    print $sv_fh "// $key : $value \n";
}

# close file handler when done
# close $fh