use warnings;
use strict;

# tried to use the file::slurp library but cpan doesn't work lol
# use File::Slurp

my $sv_file = "hdl/mp_cache_data_array_pl.sv";
my $json_file = "sram_config.json";

# read json file
open(my $json_fh)

# sram array generation in perl '>' stand for write
open(my $sv_fh, '>', $sv_file);

print $fh "// generated by pl_generate_sram.pl \n";



# close file handler when done
# close $fh