# a simple sram array generator
import sys
import json
import math

RED    = "31"
YELLOW = "33"
GREEN  = "32"
BLUE   = "36"

header = "// generated by py_generate_sram.py \n"
input_ports = ["csb", "web", "wmask", "addr", "din"]
output_ports = ["dout"]
input_header = "\tinput\tlogic\t"
output_header = "\toutput\tlogic\t"
logic_header = "\tlogic\t"


def print_color(message: str, color: str) -> None:
    print(f"\033[{color}m" + message + "\033[0m")

# def list_ports(header: str, ports: dict) -> None:


if __name__ == "__main__":
    # try to open the config file
    try:
        with open("sram_config.json", 'r') as config_file:
            # convert the config to a dict
            config = json.load(config_file)
            print(config)

            # start populating the file
            with open ("hdl/mp_cache_data_array_py.sv", 'w') as sv_file:

                # write header information
                sv_file.write(header)
                # record config info
                for key in config.keys():
                    sv_file.write(f"// {key}: {config[key]} \n")

                # start populating the module:
                sv_file.write("module mp_cache_data_array_py\n#(\n")

                # calculate params and add them
                data_width = int(config["word_size"])
                addr_width = int(math.log2(config["num_words"]))
                num_wmasks = int(data_width/8)
                ram_depth = int(config["num_words"])
                sv_file.write(f"\tparameter NUM_WMASKS = {num_wmasks},\n")
                sv_file.write(f"\tparameter DATA_WIDTH = {data_width},\n")
                sv_file.write(f"\tparameter ADDR_WIDTH = {addr_width},\n")
                sv_file.write(f"\tparameter RAM_DEPTH  = {ram_depth} \n)\n(\n")

                # start populating ports
                sv_file.write("\tinput\tlogic\tclk,\n\n")
                
                
                # for every port, generate the necessary signals
                for port_idx in range (config["num_rw_ports"]):
                    sv_file.write(f"\t// port{port_idx}\n")
                    # define all input ports
                    for port in input_ports:
                        # add addr/data width into the logic definition
                        if (port == "addr"):
                            sv_file.write(f"{input_header}[ADDR_WIDTH-1: 0]\t{port}{port_idx},\n")
                        elif (port == "din"):
                            sv_file.write(f"{input_header}[DATA_WIDTH-1: 0]\t{port}{port_idx},\n")
                        elif (port == "wmask"):
                            sv_file.write(f"{input_header}[NUM_WMASKS-1: 0]\t{port}{port_idx},\n")
                        else:
                            sv_file.write(f"{input_header}{port}{port_idx},\n")
                    
                    # define all output ports
                    for port in output_ports:
                        # define dout width
                        if (port == "dout"):
                            sv_file.write(f"{output_header}[DATA_WIDTH-1: 0]\t{port}{port_idx}")
                        else:
                            sv_file.write(f"{output_header}{port}{port_idx}")

                        # if this is not the last port we need to write, then add comma 
                        if ((port == output_ports[-1]) and (port_idx == int(config["num_rw_ports"] - 1))):
                            sv_file.write("\n")
                        else:
                            sv_file.write(",\n")

                    # separate ports with new lines
                    sv_file.write("\n")
                
                # finished writing all the ports
                sv_file.write(");\n")

                # include local logics
                for port_idx in range (config["num_rw_ports"]):
                    sv_file.write(f"\t// port{port_idx}\n")
                    # define all input ports
                    for port in input_ports:
                        # add addr/data width into the logic definition
                        if (port == "addr"):
                            sv_file.write(f"{logic_header}[ADDR_WIDTH-1: 0]\t{port}{port_idx}_reg;\n")
                        elif (port == "din"):
                            sv_file.write(f"{logic_header}[DATA_WIDTH-1: 0]\t{port}{port_idx}_reg;\n")
                        elif (port == "wmask"):
                            sv_file.write(f"{logic_header}[NUM_WMASKS-1: 0]\t{port}{port_idx}_reg;\n")
                        # elif (port == "web"):
                        #     sv_file.write(f"{logic_header}{port}{port_idx}_reg = '1;\n")
                        else:
                            sv_file.write(f"{logic_header}{port}{port_idx}_reg;\n")
                    
                    # define all output ports
                    for port in output_ports:
                        # define dout width
                        if (port == "dout"):
                            sv_file.write(f"{logic_header}[DATA_WIDTH-1: 0]\t{port}{port_idx}_reg;")
                        else:
                            sv_file.write(f"{logic_header}{port}{port_idx}_reg;")


                    # separate ports with new lines
                    sv_file.write("\n")
                # add the int for loop
                sv_file.write(f"{logic_header}[DATA_WIDTH-1: 0]\tmem [RAM_DEPTH];\n")
                sv_file.write("\tinteger\t i; \n")
                


                # generate latch logic
                sv_file.write("\n\n\t// latch input value")
                sv_file.write("\n\talways_ff @ (posedge clk) begin\n")
                for port_idx in range (config["num_rw_ports"]):
                    sv_file.write(f"\t\tif (!csb{port_idx}) begin\n")
                    sv_file.write(f"\t\t\tweb{port_idx}_reg <= web{port_idx};\n")
                    sv_file.write(f"\t\t\twmask{port_idx}_reg <= wmask{port_idx};\n")
                    sv_file.write(f"\t\t\taddr{port_idx}_reg <= addr{port_idx};\n")
                    sv_file.write(f"\t\t\tdin{port_idx}_reg <= din{port_idx};\n")
                    sv_file.write(f"\t\tend\n")
                sv_file.write("\tend\n\n\n")

                # generate write logic
                sv_file.write("\n\talways_ff @ (posedge clk) begin\n")
                for port_idx in range (config["num_rw_ports"]):
                    sv_file.write(f"\t\tif (!web{port_idx}_reg) begin\n")

                    #* the following method hardcode all write cases. Prob better to use a for loop

                    for idx in range (num_wmasks):
                        sv_file.write(f"\t\t\tif (wmask{port_idx}_reg[{idx}]) \n")
                        sv_file.write(f"\t\t\t\tmem[addr{port_idx}_reg][{idx * 8 + 7}:{idx * 8}] <= din{port_idx}_reg[{idx * 8 + 7}:{idx * 8}];\n")

                    # generate a for loop instead:
                    # sv_file.write(f"\t\t\tfor (i = 0; i <= NUM_WMASKS; i = i + 1) begin\n")
                    # sv_file.write(f"\t\t\t\tif (wmask{port_idx}_reg[i]) \n")
                    # sv_file.write(f"\t\t\t\t\tmem[addr{port_idx}_reg][(i * 8 )+ 7:i * 8] <= din{port_idx}_reg[(i * 8) + 7:i * 8];\n")
                    # sv_file.write(f"\t\t\tend\n")
                    # end if (!web_reg)    
                    sv_file.write(f"\t\tend\n")
                #end whole always_ff
                sv_file.write(f"\tend\n\n")

                # generate read logic
                for port_idx in range (config["num_rw_ports"]):
                    sv_file.write(f"\tassign dout{port_idx} = mem[addr{port_idx}_reg];")
                


                # finish module
                sv_file.write("\nendmodule")
                



    # throw error
    except FileNotFoundError:
        print_color("file not found", RED)
        sys.exit(1)